#!/usr/bin/env python3
"""Generate the TypeScript protocol types from the Pydantic contracts.

    python scripts/gen_rpc_contracts.py            # rewrite apps/shared/src/contracts.generated.ts
    python scripts/gen_rpc_contracts.py --check    # exit 1 if the file is out of date (CI)

The Python contracts in ``src/clite/rpc/contracts/schema.py`` are the single source of truth.
Never edit the generated file by hand: change the contract, then run this script.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from pydantic import BaseModel  # noqa: E402

from clite.rpc.contracts import schema  # noqa: E402, F401 - importing registers everything
from clite.rpc.contracts.base import EVENTS, METHODS, PROTOCOL_VERSION, SERVER_REQUESTS  # noqa: E402

OUTPUT = ROOT / "apps" / "shared" / "src" / "contracts.generated.ts"
_PRIMITIVES = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}


def ts_type(node: dict[str, Any]) -> str:
    """A JSON-schema fragment as a TypeScript type expression."""
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "enum" in node:
        return " | ".join(repr_literal(value) for value in node["enum"])
    if "const" in node:
        return repr_literal(node["const"])
    for key in ("anyOf", "oneOf"):
        if key in node:
            return " | ".join(dict.fromkeys(ts_type(option) for option in node[key]))
    kind = node.get("type")
    if kind == "array":
        inner = ts_type(node.get("items") or {})
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if kind == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict) and extra:
            return f"Record<string, {ts_type(extra)}>"
        return "Record<string, unknown>"
    if kind in _PRIMITIVES:
        return _PRIMITIVES[kind]
    return "unknown"


def repr_literal(value: Any) -> str:
    return '"' + str(value).replace('"', '\\"') + '"' if isinstance(value, str) else str(value).lower()


def interface(model: type[BaseModel], definitions: dict[str, str], *, sent_by_client: bool) -> str:
    """Emit ``model`` (and, into ``definitions``, every model it references)."""
    document = model.model_json_schema(ref_template="#/$defs/{model}")
    nested = document.get("$defs", {})
    for name, body in nested.items():
        definitions.setdefault(name, render(name, body, optional_defaults=False))
    return render(model.__name__, document, optional_defaults=sent_by_client)


def render(name: str, document: dict[str, Any], *, optional_defaults: bool) -> str:
    properties = document.get("properties") or {}
    required = set(document.get("required") or [])
    lines = [f"export interface {name} {{"]
    for field, node in properties.items():
        # A client may omit a request field that has a default. A server always sends
        # every field of a result or an event, so those are never optional.
        optional = "?" if optional_defaults and field not in required else ""
        lines.append(f"  {field}{optional}: {ts_type(node)};")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    definitions: dict[str, str] = {}
    # Which side writes a model decides whether its defaulted fields are optional in
    # TypeScript: the client may omit them, the server never does.
    models: dict[str, tuple[type[BaseModel], bool]] = {}
    for spec in METHODS.values():
        models[spec.params.__name__] = (spec.params, True)
        models.setdefault(spec.result.__name__, (spec.result, False))
    for spec in SERVER_REQUESTS.values():
        models[spec.params.__name__] = (spec.params, False)
        models[spec.result.__name__] = (spec.result, True)
    for payload in EVENTS.values():
        models.setdefault(payload.__name__, (payload, False))
    for name in sorted(models):
        model, sent_by_client = models[name]
        definitions[name] = interface(model, definitions, sent_by_client=sent_by_client)

    out = [
        "// GENERATED by scripts/gen_rpc_contracts.py from src/clite/rpc/contracts/schema.py.",
        "// Do not edit. Change the Python contract and regenerate.",
        "",
        f"export const PROTOCOL_VERSION = {PROTOCOL_VERSION};",
        "",
    ]
    out += [definitions[name] + "\n" for name in sorted(definitions)]

    out.append("/** Client-to-server methods. */")
    out.append("export interface Methods {")
    for name, spec in METHODS.items():
        if spec.description:
            out.append(f"  /** {spec.description} */")
        out.append(f'  "{name}": {{ params: {spec.params.__name__}; result: {spec.result.__name__} }};')
    out.append("}\n")

    out.append("/** Events the server emits, by `type`. */")
    out.append("export interface Events {")
    out += [f'  "{name}": {payload.__name__};' for name, payload in EVENTS.items()]
    out.append("}\n")

    out.append("/** Requests the server sends and the client must answer. */")
    out.append("export interface ServerRequests {")
    for name, spec in SERVER_REQUESTS.items():
        if spec.description:
            out.append(f"  /** {spec.description} */")
        out.append(f'  "{name}": {{ params: {spec.params.__name__}; result: {spec.result.__name__} }};')
    out.append("}\n")

    out.append(f"export const METHOD_NAMES = [{', '.join(repr_literal(name) for name in METHODS)}] as const;")
    out.append(f"export const EVENT_TYPES = [{', '.join(repr_literal(name) for name in EVENTS)}] as const;")
    out.append(f"export const SERVER_REQUEST_NAMES = [{', '.join(repr_literal(name) for name in SERVER_REQUESTS)}] as const;")
    out.append("")
    out.append("export type MethodName = keyof Methods;")
    out.append("export type EventType = keyof Events;")
    out.append("export type ServerRequestName = keyof ServerRequests;")
    out.append("")
    out.append("/** The envelope of every event notification. */")
    out.append("export type EventEnvelope = {")
    out.append("  [T in EventType]: { type: T; session_id: string; payload: Events[T]; seq: number };")
    out.append("}[EventType];")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated file is out of date")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date. Run: python scripts/gen_rpc_contracts.py", file=sys.stderr)
            return 1
        print("contracts are up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(METHODS)} methods, {len(EVENTS)} events, {len(SERVER_REQUESTS)} server requests)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
