// GENERATED by scripts/gen_rpc_contracts.py from src/clite/rpc/contracts/schema.py.
// Do not edit. Change the Python contract and regenerate.

export const PROTOCOL_VERSION = 1;

export interface ApprovalRequestParams {
  session_id: string;
  command: string;
  description: string;
  pattern_keys: string[];
}

export interface ApprovalRequestResult {
  choice: "once" | "session" | "always" | "deny";
}

export interface CatalogParams {
  session_id?: string | null;
}

export interface CatalogResult {
  commands: CommandEntry[];
}

export interface ClarifyRequestParams {
  session_id: string;
  question: string;
  choices: string[];
}

export interface ClarifyRequestResult {
  answer?: string;
}

export interface CommandEntry {
  name: string;
  description: string;
  category: string;
  aliases: string[];
  args_hint: string;
  subcommands: string[];
  kind: string;
}

export interface CompleteParams {
  prefix: string;
  session_id?: string | null;
}

export interface CompleteResult {
  items: CommandEntry[];
}

export interface ConfigGetParams {
  key?: string | null;
}

export interface ConfigGetResult {
  value: unknown;
}

export interface ConfigSetParams {
  key: string;
  value?: unknown;
}

export interface ContextStatus {
  engine: string;
  context_length: number;
  threshold_tokens: number;
  last_prompt_tokens: number;
  compression_count: number;
  usage_percent: number;
  messages: number;
  model: string;
  provider: string;
}

export interface CronActionParams {
  job_id: string;
  action: "pause" | "resume" | "run" | "remove";
}

export interface CronCreateParams {
  prompt: string;
  schedule: string;
  name?: string;
  deliver?: string;
  repeat?: number | null;
}

export interface CronJob {
  id: string;
  name: string;
  prompt: string;
  schedule_display: string;
  enabled: boolean;
  deliver: string;
  next_run_at: number | null;
  last_run_at: number | null;
  last_status: string | null;
  last_error: string | null;
  run_count: number;
}

export interface CronListResult {
  jobs: CronJob[];
}

export interface Empty {
}

export interface ErrorPayload {
  message: string;
  code: number;
}

export interface MemoryGetResult {
  memory: string[];
  user: string[];
  memory_limit: number;
  user_limit: number;
  provider: string;
}

export interface MessagePayload {
  role: string;
  text: string;
  tool_calls: string[];
}

export interface ModelEntry {
  id: string;
  context_length: number | null;
}

export interface ModelListParams {
  provider?: string | null;
  refresh?: boolean;
}

export interface ModelListResult {
  provider: string;
  models: ModelEntry[];
  current: string;
}

export interface ModelSetParams {
  session_id: string;
  model: string;
  persist?: boolean;
}

export interface ModelSetResult {
  success: boolean;
  message: string;
  model: string;
  provider: string;
}

export interface Ok {
  ok: boolean;
}

export interface PingResult {
  pong: boolean;
  version: string;
}

export interface PluginEntry {
  name: string;
  version: string;
  description: string;
  kind: string;
  source: string;
  status: string;
  error: string;
  path: string;
}

export interface PluginSetEnabledParams {
  name: string;
  enabled: boolean;
}

export interface PluginsListResult {
  plugins: PluginEntry[];
}

export interface PromptSubmitParams {
  session_id: string;
  text: string;
  busy_mode?: "interrupt" | "queue" | "steer" | "reject" | null;
}

export interface PromptSubmitResult {
  accepted: boolean;
  turn_id: string;
  queued: boolean;
}

export interface ProviderEntry {
  name: string;
  display_name: string;
  description: string;
  configured: boolean;
  env_vars: string[];
  needs_base_url: boolean;
  signup_url: string;
}

export interface ProvidersResult {
  providers: ProviderEntry[];
  current: string;
}

export interface ReadyPayload {
  version: string;
  protocol_version: number;
}

export interface SessionCompressParams {
  session_id: string;
  focus?: string | null;
}

export interface SessionCompressResult {
  compressed: boolean;
  message_count: number;
}

export interface SessionCreateParams {
  cwd?: string | null;
  model?: string | null;
  provider?: string | null;
  toolsets?: string[] | null;
  yolo?: boolean;
  resume?: string | null;
  platform?: string | null;
}

export interface SessionDeleteParams {
  stored_session_id: string;
}

export interface SessionHistoryResult {
  messages: TranscriptMessage[];
}

export interface SessionInfo {
  session_id: string;
  stored_session_id: string;
  title: string;
  platform: string;
  model: string;
  provider: string;
  cwd: string;
  busy: boolean;
  yolo: boolean;
  message_count: number;
  tools: string[];
  toolsets: string[];
  reasoning_effort: string;
  context: ContextStatus;
}

export interface SessionListParams {
  limit?: number;
  source?: string | null;
}

export interface SessionListResult {
  sessions: StoredSession[];
}

export interface SessionRef {
  session_id: string;
}

export interface SessionSteerParams {
  session_id: string;
  text: string;
}

export interface SessionTitleParams {
  session_id: string;
  title?: string | null;
}

export interface SessionTitleResult {
  title: string;
}

export interface SessionUsageResult {
  usage: UsageTotals;
  context: ContextStatus;
}

export interface SetupApplyParams {
  provider: string;
  api_key?: string | null;
  model?: string | null;
  base_url?: string | null;
}

export interface SetupApplyResult {
  provider: string;
  model: string;
}

export interface SkillEntry {
  name: string;
  description: string;
  category: string;
  tier: string;
  version: string;
  tags: string[];
}

export interface SkillViewParams {
  name: string;
  file_path?: string | null;
}

export interface SkillViewResult {
  name: string;
  content: string;
  linked_files: Record<string, string[]>;
}

export interface SkillsListResult {
  skills: SkillEntry[];
}

export interface SlashExecParams {
  session_id: string;
  command: string;
}

export interface SlashExecResult {
  text: string;
  action: string | null;
  turn_id: string;
  data: Record<string, unknown>;
}

export interface StatusPayload {
  kind: string;
  text: string;
}

export interface StepPayload {
  iteration: number;
}

export interface StoredSession {
  id: string;
  title: string;
  source: string;
  model: string;
  message_count: number;
  started_at: number;
  last_activity_at: number | null;
}

export interface SubagentPayload {
  event: string;
  index: number;
  goal: string;
  tool: string;
  status: string;
}

export interface SystemInfoResult {
  version: string;
  protocol_version: number;
  home: string;
  profile: string;
  configured: boolean;
  model: string;
  provider: string;
}

export interface TextPayload {
  text: string;
}

export interface ToolCompletePayload {
  call_id: string;
  name: string;
  duration: number;
  failed: boolean;
  result_preview: string;
}

export interface ToolStartPayload {
  call_id: string;
  name: string;
  args: Record<string, unknown>;
  preview: string;
}

export interface ToolsListResult {
  toolsets: ToolsetEntry[];
}

export interface ToolsetEntry {
  name: string;
  description: string;
  tools: string[];
  enabled_tools: string[];
}

export interface TranscriptMessage {
  role: "user" | "assistant" | "tool" | "system";
  text: string;
  tool_name: string;
  tool_calls: string[];
  is_summary: boolean;
  timestamp: number | null;
}

export interface TurnCompletePayload {
  turn_id: string;
  final_response: string;
  completed: boolean;
  interrupted: boolean;
  error: string | null;
  exit_reason: string;
  api_calls: number;
  duration: number;
  usage: UsageTotals;
}

export interface TurnStartPayload {
  turn_id: string;
  text: string;
}

export interface UsageTotals {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens: number;
  cache_write_tokens: number;
  reasoning_tokens: number;
  prompt_tokens: number;
}

/** Client-to-server methods. */
export interface Methods {
  /** Liveness check. */
  "ping": { params: Empty; result: PingResult };
  /** Version, active profile and whether a model is configured. */
  "system.info": { params: Empty; result: SystemInfoResult };
  /** Open a runtime session (new, or resuming a stored one). */
  "session.create": { params: SessionCreateParams; result: SessionInfo };
  "session.info": { params: SessionRef; result: SessionInfo };
  /** Stored sessions, most recent first. */
  "session.list": { params: SessionListParams; result: SessionListResult };
  /** The transcript, in display form. */
  "session.history": { params: SessionRef; result: SessionHistoryResult };
  "session.close": { params: SessionRef; result: Ok };
  /** Stop the running turn. */
  "session.interrupt": { params: SessionRef; result: Ok };
  /** Guide the running turn without stopping it. */
  "session.steer": { params: SessionSteerParams; result: Ok };
  /** Read the title, or set it when `title` is given. */
  "session.title": { params: SessionTitleParams; result: SessionTitleResult };
  "session.delete": { params: SessionDeleteParams; result: Ok };
  "session.compress": { params: SessionCompressParams; result: SessionCompressResult };
  "session.usage": { params: SessionRef; result: SessionUsageResult };
  /** Start a turn. Returns at once; the answer arrives as events ending with turn.complete. */
  "prompt.submit": { params: PromptSubmitParams; result: PromptSubmitResult };
  /** Run a slash command. */
  "slash.exec": { params: SlashExecParams; result: SlashExecResult };
  /** Every command available now, for help and autocomplete. */
  "commands.catalog": { params: CatalogParams; result: CatalogResult };
  /** Commands starting with a prefix. */
  "complete.slash": { params: CompleteParams; result: CompleteResult };
  /** One value by dotted key, or the whole effective config. */
  "config.get": { params: ConfigGetParams; result: ConfigGetResult };
  "config.set": { params: ConfigSetParams; result: Ok };
  "model.list": { params: ModelListParams; result: ModelListResult };
  /** Switch the session's model; `persist` saves it as the default. */
  "model.set": { params: ModelSetParams; result: ModelSetResult };
  "providers.list": { params: Empty; result: ProvidersResult };
  /** Store a provider choice (and its API key) from a setup screen. */
  "setup.apply": { params: SetupApplyParams; result: SetupApplyResult };
  "tools.list": { params: CatalogParams; result: ToolsListResult };
  "skills.list": { params: Empty; result: SkillsListResult };
  "skills.view": { params: SkillViewParams; result: SkillViewResult };
  "plugins.list": { params: Empty; result: PluginsListResult };
  "plugins.set_enabled": { params: PluginSetEnabledParams; result: PluginsListResult };
  "memory.get": { params: Empty; result: MemoryGetResult };
  "cron.list": { params: Empty; result: CronListResult };
  "cron.create": { params: CronCreateParams; result: CronJob };
  "cron.action": { params: CronActionParams; result: CronListResult };
}

/** Events the server emits, by `type`. */
export interface Events {
  "gateway.ready": ReadyPayload;
  "session.info": SessionInfo;
  "turn.start": TurnStartPayload;
  "turn.step": StepPayload;
  "message.delta": TextPayload;
  "reasoning.delta": TextPayload;
  "message.complete": MessagePayload;
  "tool.start": ToolStartPayload;
  "tool.complete": ToolCompletePayload;
  "status.update": StatusPayload;
  "subagent.update": SubagentPayload;
  "turn.complete": TurnCompletePayload;
  "error": ErrorPayload;
}

/** Requests the server sends and the client must answer. */
export interface ServerRequests {
  /** A dangerous command needs the user's decision. No reply within the timeout means deny. */
  "approval.request": { params: ApprovalRequestParams; result: ApprovalRequestResult };
  /** The agent asks the user a question. */
  "clarify.request": { params: ClarifyRequestParams; result: ClarifyRequestResult };
}

export const METHOD_NAMES = ["ping", "system.info", "session.create", "session.info", "session.list", "session.history", "session.close", "session.interrupt", "session.steer", "session.title", "session.delete", "session.compress", "session.usage", "prompt.submit", "slash.exec", "commands.catalog", "complete.slash", "config.get", "config.set", "model.list", "model.set", "providers.list", "setup.apply", "tools.list", "skills.list", "skills.view", "plugins.list", "plugins.set_enabled", "memory.get", "cron.list", "cron.create", "cron.action"] as const;
export const EVENT_TYPES = ["gateway.ready", "session.info", "turn.start", "turn.step", "message.delta", "reasoning.delta", "message.complete", "tool.start", "tool.complete", "status.update", "subagent.update", "turn.complete", "error"] as const;
export const SERVER_REQUEST_NAMES = ["approval.request", "clarify.request"] as const;

export type MethodName = keyof Methods;
export type EventType = keyof Events;
export type ServerRequestName = keyof ServerRequests;

/** The envelope of every event notification. */
export type EventEnvelope = {
  [T in EventType]: { type: T; session_id: string; payload: Events[T]; seq: number };
}[EventType];
